### ISSUE TITLE
FAQ text isn't responsive and splits words oddly when wrapping text

### ISSUE THREAD

**Issue by lauratinnel** [ITI/searcch#142] opened 2022-09-08 11:56 UTC
**Describe the bug**
FAQ  window is too narrow, isn't responsive, and splits words oddly when wrapping text

**To Reproduce**
View the FAQ and look at "I have code, data, and other artifacts that are all from the same research. How should I submit those to the hub?". The word "research" is split as "resear" and "ch". 

**Expected behavior**
Resizing the window should change the size of the text box. Carriage return should be inserted before the word if there's not enough space on the line for the entire word. 

**Screenshots**
See screen shot

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 104.0.1 64-bit

**Additional context**
Overall, the text box width is fixed and too narrow. The box should be responsive and resize when you resize the screen.

![Screen Shot 2022-09-08 at 7 53 07 AM](https://user-images.githubusercontent.com/3372750/189115400-539b69c1-cdbb-4d66-8c59-7f9d725755d8.png)

**Comment by lauratinnel** [comment] 2022-09-08 17:19
Looks like the hub-dev has a responsive version of this page. But the line breaks are still off.

**Comment by yashshah15** [comment] 2022-09-27 19:22
Can't reproduce the issue right now. Please reproduce if it reappears or if someone else can reproduce it. Closing it for now.

**Closed as completed by yashshah15** 2022-09-27 19:22 UTC
Labels: bug, priority: medium
